export type UserProfile = {
  id: string;
  name: string;
  email: string;
  emailVerified: string;
  password: string;
  image: string | null;
  role: "ADMIN" | "USER"
  isActive: boolean;
  firstName: string | null;
  lastName: string | null;
  displayName: string | null;
  gender: string | null;
  dateOfBirth: string | null;
  phoneNumber: string | null;
  address: string | null;
  city: string | null;
  state: string | null;
  country: string | null;
  postalCode: string | null;
  company: string | null;
  jobTitle: string | null;
  department: string | null;
  language: string;
  timezone: string;
  currency: string;
  emailNotifications: boolean;
  smsNotifications: boolean;
  linkedinUrl: string | null;
  twitterUrl: string | null;
  websiteUrl: string | null;
  lastLoginAt: string | null;
  createdAt: string;
  updatedAt: string;
};